language: node_js

node_js:
  - "lts/*"

services:
  - docker

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "npm install ep_test_line_attrib"

before_script:
  - "tests/frontend/travis/sauce_tunnel.sh"

script:
  - "tests/frontend/travis/runner.sh"

env:
  global:
    - IMAGE_NAME=etherpad:test
    - secure: "WMGxFkOeTTlhWB+ChMucRtIqVmMbwzYdNHuHQjKCcj8HBEPdZLfCuK/kf4rG\nVLcLQiIsyllqzNhBGVHG1nyqWr0/LTm8JRqSCDDVIhpyzp9KpCJQQJG2Uwjk\n6/HIJJh/wbxsEdLNV2crYU/EiVO3A4Bq0YTHUlbhUqG3mSCr5Ec="
    - secure: "gejXUAHYscbR6Bodw35XexpToqWkv2ifeECsbeEmjaLkYzXmUUNWJGknKSu7\nEUsSfQV8w+hxApr1Z+jNqk9aX3K1I4btL3cwk2trnNI8XRAvu1c1Iv60eerI\nkE82Rsd5lwUaMEh+/HoL8ztFCZamVndoNgX7HWp5J/NRZZMmh4g="

jobs:
  include:
    - name: "Run the Backend tests"
      install:
        - "cd src && npm install && cd -"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Test the Frontend"
      install:
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
        - "npm install ep_test_line_attrib"
      script:
        - "tests/frontend/travis/runner.sh"
    - name: "Test the Dockerfile"
      install:
        - "cd src && npm install && cd -"
      script:
        - "docker build -t ${IMAGE_NAME} ."
        - "docker run -d -p 9001:9001 ${IMAGE_NAME} && sleep 3"
        - "cd src && npm run test-container"
    - name: "Test a docker-compose with MySQL"
      install:
        - "cd src && npm install && cd -"
      script:
        - "docker-compose -f docker-compose_mysql.yml build"
        - "docker-compose -f docker-compose_mysql.yml up -d && sleep 60"
        - "cd src && npm run test-container"
    - name: "Test a docker-compose with PostgreSQL"
      install:
        - "cd src && npm install && cd -"
      script:
        - "docker-compose -f docker-compose_postgresql.yml build"
        - "docker-compose -f docker-compose_postgresql.yml up -d && sleep 30"
        - "cd src && npm run test-container"

notifications:
  irc:
    channels:
      - "irc.freenode.org#etherpad-lite-dev"
